In [93]:
import os
import pandas as pd
from tqdm import tqdm

### 1. Combining the Dataset with Individual Product Data

In [94]:
files = []

for i in os.listdir('checkpoints_adv/'): 
    if (i != '.DS_Store'):
        files.append(int(i.split('.')[0]))
        
files = sorted(files)

df = pd.DataFrame()


for i in files:
    file_path = 'checkpoints_adv/' + str(i) + '.csv'
    
    df_ = pd.read_csv(file_path)  
    df = pd.concat((df_,df))

df.head()

,prod_link,tags,seller_address,meta_description,meta_keyword
0,shirts/greenfibre/greenfibre-men-yellow-slim-f...,"['clothing', 'men-clothing', 'shirts', 'greenf...","25-28, Pariseema Complex,Nr. Lal Bunglow Cross...",Buy Greenfibre Men Yellow Slim Fit Checked Cas...,Greenfibre Men Yellow Slim Fit Checked Casual ...
1,tshirts/freesoul/freesoul-men-white-printed-co...,"['clothing', 'men-clothing', 'tshirts', 'frees...","21-E1,2ND PHASE, PEENYA INDUSTRIAL AREA,Bengal...",Buy FREESOUL Men White Printed Cotton T Shirt ...,"FREESOUL Men White Printed Cotton T Shirt, FR..."
2,wallets/da-milano/da-milano-women-blue-texture...,"['accessories', 'women-accessories', 'wallets'...","85, Kapashera Bijwasan Road, New DelhiNew Delh...",Buy Da Milano Women Blue Textured Leather Two ...,Da Milano Women Blue Textured Leather Two Fold...
3,sarees/mitera/mitera-women-sea-green--white-em...,"['clothing', 'women-clothing', 'sarees', 'mite...","7007, Hindustan Textile Centre-2,Dumbhal,Surat...",Buy Mitera Women Sea Green & White Embroidered...,Mitera Women Sea Green & White Embroidered Pur...
4,kurtas/indo-era/indo-era-men-lavender-geometri...,"['clothing', 'men-clothing', 'kurtas', 'indo-e...","4TH FLOOR, Block No B-4021/4022/4023/4026/4038...",Buy Indo Era Men Lavender Geometric Printed Ku...,"Indo Era Men Lavender Geometric Printed Kurta,..."

### 2. Load Main Product Data

In [95]:
df_ = pd.read_csv('data.csv')

### 3. Combining the Dataset

In [98]:
titles = ['product_name','brand_name','rating','rating_count','marked_price','discounted_price',
          'sizes','product_link','img_link','product_tag','brand_tag','discount_amount','discount_percent',
          'tags','seller_address','meta_description','mera_keyword']

data = []

for i in tqdm(df.values):
    data.append(list(df_[df_['product_link'] == i[0]].values[0]) + list(i[1:]))

100%|████████████████████████████████████| 24324/24324 [03:32<00:00, 114.67it/s]

### 4. Creating the DataFrame

In [101]:
df = pd.DataFrame(data, columns = ['product_name','brand_name','rating','rating_count','marked_price',
                                   'discounted_price', 'sizes','product_link','img_link','product_tag',
                                   'brand_tag','discount_amount','discount_percent', 'tags'
                                   ,'seller_address','meta_description','meta_keyword'])

df.head()

,product_name,brand_name,rating,rating_count,marked_price,discounted_price,sizes,product_link,img_link,product_tag,brand_tag,discount_amount,discount_percent,tags,seller_address,meta_description,meta_keyword
0,Slim Fit Casual Shirt,Greenfibre,0.0,0,1699,1699,"38,39,40,42,44",shirts/greenfibre/greenfibre-men-yellow-slim-f...,"https://assets.myntassets.com/dpr_2,q_60,w_210...",shirts,greenfibre,0,0,"['clothing', 'men-clothing', 'shirts', 'greenf...","25-28, Pariseema Complex,Nr. Lal Bunglow Cross...",Buy Greenfibre Men Yellow Slim Fit Checked Cas...,Greenfibre Men Yellow Slim Fit Checked Casual ...
1,Men Printed T-shirt,FREESOUL,0.0,0,799,799,"S,M,L,XL,XXL",tshirts/freesoul/freesoul-men-white-printed-co...,"https://assets.myntassets.com/dpr_2,q_60,w_210...",tshirts,freesoul,0,0,"['clothing', 'men-clothing', 'tshirts', 'frees...","21-E1,2ND PHASE, PEENYA INDUSTRIAL AREA,Bengal...",Buy FREESOUL Men White Printed Cotton T Shirt ...,"FREESOUL Men White Printed Cotton T Shirt, FR..."
2,Leather Two Fold Wallet,Da Milano,0.0,0,4499,4499,Onesize,wallets/da-milano/da-milano-women-blue-texture...,"https://assets.myntassets.com/dpr_2,q_60,w_210...",wallets,da-milano,0,0,"['accessories', 'women-accessories', 'wallets'...","85, Kapashera Bijwasan Road, New DelhiNew Delh...",Buy Da Milano Women Blue Textured Leather Two ...,Da Milano Women Blue Textured Leather Two Fold...
3,Pure Georgette Bandhani Saree,Mitera,3.6,5,6727,1681,Onesize,sarees/mitera/mitera-women-sea-green--white-em...,"https://assets.myntassets.com/dpr_2,q_60,w_210...",sarees,mitera,5046,75,"['clothing', 'women-clothing', 'sarees', 'mite...","7007, Hindustan Textile Centre-2,Dumbhal,Surat...",Buy Mitera Women Sea Green & White Embroidered...,Mitera Women Sea Green & White Embroidered Pur...
4,Men Geometric Printed Kurta,Indo Era,0.0,0,2599,1429,"S,M,L,XL,XXL",kurtas/indo-era/indo-era-men-lavender-geometri...,"https://assets.myntassets.com/dpr_2,q_60,w_210...",kurtas,indo-era,1170,45,"['clothing', 'men-clothing', 'kurtas', 'indo-e...","4TH FLOOR, Block No B-4021/4022/4023/4026/4038...",Buy Indo Era Men Lavender Geometric Printed Ku...,"Indo Era Men Lavender Geometric Printed Kurta,..."

### 5. Data Preprocessing

In [126]:
df['tags'] = df['tags'].fillna("['Not Specified']")


tags = []

for i in df['tags']:
    tags.append(','.join([_.replace("'",'').strip() for _ in i[2:-2].split(',')]))
    
df['tags'] = tags

df.head()

,product_name,brand_name,rating,rating_count,marked_price,discounted_price,sizes,product_link,img_link,product_tag,brand_tag,discount_amount,discount_percent,tags,seller_address,meta_description,meta_keyword
0,Slim Fit Casual Shirt,Greenfibre,0.0,0,1699,1699,"38,39,40,42,44",shirts/greenfibre/greenfibre-men-yellow-slim-f...,"https://assets.myntassets.com/dpr_2,q_60,w_210...",shirts,greenfibre,0,0,"clothing,men-clothing,shirts,greenfibre-shirts","25-28, Pariseema Complex,Nr. Lal Bunglow Cross...",Buy Greenfibre Men Yellow Slim Fit Checked Cas...,Greenfibre Men Yellow Slim Fit Checked Casual ...
1,Men Printed T-shirt,FREESOUL,0.0,0,799,799,"S,M,L,XL,XXL",tshirts/freesoul/freesoul-men-white-printed-co...,"https://assets.myntassets.com/dpr_2,q_60,w_210...",tshirts,freesoul,0,0,"clothing,men-clothing,tshirts,freesoul-tshirts","21-E1,2ND PHASE, PEENYA INDUSTRIAL AREA,Bengal...",Buy FREESOUL Men White Printed Cotton T Shirt ...,"FREESOUL Men White Printed Cotton T Shirt, FR..."
2,Leather Two Fold Wallet,Da Milano,0.0,0,4499,4499,Onesize,wallets/da-milano/da-milano-women-blue-texture...,"https://assets.myntassets.com/dpr_2,q_60,w_210...",wallets,da-milano,0,0,"accessories,women-accessories,wallets,da-milan...","85, Kapashera Bijwasan Road, New DelhiNew Delh...",Buy Da Milano Women Blue Textured Leather Two ...,Da Milano Women Blue Textured Leather Two Fold...
3,Pure Georgette Bandhani Saree,Mitera,3.6,5,6727,1681,Onesize,sarees/mitera/mitera-women-sea-green--white-em...,"https://assets.myntassets.com/dpr_2,q_60,w_210...",sarees,mitera,5046,75,"clothing,women-clothing,sarees,mitera-sarees","7007, Hindustan Textile Centre-2,Dumbhal,Surat...",Buy Mitera Women Sea Green & White Embroidered...,Mitera Women Sea Green & White Embroidered Pur...
4,Men Geometric Printed Kurta,Indo Era,0.0,0,2599,1429,"S,M,L,XL,XXL",kurtas/indo-era/indo-era-men-lavender-geometri...,"https://assets.myntassets.com/dpr_2,q_60,w_210...",kurtas,indo-era,1170,45,"clothing,men-clothing,kurtas,indo-era-kurtas","4TH FLOOR, Block No B-4021/4022/4023/4026/4038...",Buy Indo Era Men Lavender Geometric Printed Ku...,"Indo Era Men Lavender Geometric Printed Kurta,..."

### 6. Removing Null Values

In [128]:
df['seller_address']    = df['seller_address'].fillna('Not Mentioned')
df['meta_description']  = df['meta_description'].fillna('Not Mentioned')
df['meta_keyword']      = df['meta_keyword'].fillna('Not Mentioned')

### 6. Saving the Dataset into CSV

In [131]:
df.to_csv('products.csv', index = False)